apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  nodeSelector:
    gpu-node: "true"
  containers:
  - name: gpu-container
    image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1